%
% Convert test .P files to binned data
% For Rota 2022 data
%
% Aug-2023, Pat Welch, pat@mousebrains.com

my_root = fileparts(mfilename("fullpath"));
code_root = fullfile(my_root, "../Code");
data_root = "~/Desktop/Wake2023/Data 2022";
p_file_root = fullfile(data_root, "Pfiles");
output_root = fullfile(data_root, "Temp");

addpath(code_root, "-begin"); % Before reference to GPS_from_mat

GPS_filename = fullfile(data_root, "GPS/tsg.mat");
GPS_class = GPS_from_mat(GPS_filename, "M");

process_P_files( ...
    "debug", true, ...
    "gps_class", GPS_class, ... % Where to get GPS data from
    "p_file_root", p_file_root, ... % Where the input .P files are located
    "p_file_pattern", "*", ...   % Glob pattern appended to p_file_root to locate P files
    "output_root", output_root, ...  % Where to write output to
    "diss_epsilon_minimum", 3e-10, ...   % Drop dissipation estimates smaller than this value
    "netCDF_contributor_name", "Pat Welch", ...
    "netCDF_contributor_role", "researcher", ...
    "netCDF_creator_name", "Pat Welch", ...
    "netCDF_creator_email", "pat@mousebrains.com", ...
    "netCDF_creator_institution", "CEOAS, Oregon State University", ...
    "netCDF_creator_type", "researcher", ...
    "netCDF_creator_url", "https://arcterx.ceoas.oregonstat.edu", ...
    "netCDF_id", "Wake ARCTERX 2023", ...
    "netCDF_institution", "CEOAS, Oregon State University", ...
    "netCDF_platform", "Rockland VMP250", ...
    "netCDF_product_version", "0.1", ...
    "netCDF_program", "Wake ARCTERX 2023", ...
    "netCDF_project", "Wake ARCTERX 2023" ...
    );

rmpath(code_root);
