%
% Convert test .P files to binned data
%
% August-2023, Pat Welch, pat@mousebrains.com

my_root = fileparts(mfilename("fullpath"));
code_root = fullfile(my_root, "../Code");
data_root = fullfile(my_root, "../Data");
p_file_root = fullfile(data_root, "VMP");
output_root = fullfile(my_root, "../Temp");

addpath(code_root, "-begin"); % Before reference to GPS_from_csv

GPS_filename = fullfile(data_root, "GPS/gps.csv");
GPS_class = GPS_from_csv(GPS_filename);

pars = process_P_files( ...
    "debug", true, ...
    "p_file_root", p_file_root, ... % Where the input .P files are located
    "p_file_pattern", "SN*/*", ...  % Glob pattern appended to p_file_root to locate P files
    "output_root", output_root, ... % Where to write output to
    "gps_class", GPS_class, ... % Class to supply GPS data
    "diss_epsilon_minimum", 1e-11, ...   % Drop dissipation estimates smaller than this value
    "netCDF_acknowledgement", "Sample Acknowledgement", ...
    "netCDF_comment", "Sample comment", ...
    "netCDF_contributor_name", "B. McClown", ...
    "netCDF_contributor_role", "researcher", ...
    "netCDF_creator_name", "B. McClown", ...
    "netCDF_creator_email", "B.McClown@circus.edu", ...
    "netCDF_creator_institution", "CEOAS, Circus University", ...
    "netCDF_creator_type", "person", ...
    "netCDF_creator_url", "https://cfconventions.org", ...
    "netCDF_id", "Test_of_software_suite", ...
    "netCDF_institution", "CEOAS, Circus University", ...
    "netCDF_instrument", "Rockland VMP250", ...
    "netCDF_instrument_vocabulary", "turbulence,seawater", ...
    "netCDF_keywords", "Software,MicroStructure", ...
    "netCDF_keywords_vocabulary", "Clowns_are_funny", ...
    "netCDF_license", "GPLv3", ...
    "netCDF_metadata_link", "https://cfconventions.org", ...
    "netCDF_platform", "Rockland VMP250", ...
    "netCDF_platform_vocabulary", "Clowns are funny", ...
    "netCDF_product_version", "0.1", ...
    "netCDF_program", "Test of software suite", ...
    "netCDF_project", "Test of software suite", ...
    "netCDF_publisher_email", "B.McClown@circus.edu", ...
    "netCDF_publisher_institution", "Circus University", ...
    "netCDF_publisher_name", "B. McClown", ...
    "netCDF_publisher_type", "group", ...
    "netCDF_publisher_url", "https://cfconventions.org", ...
    "netCDF_references", "Clowns U.", ...
    "netCDF_source", "Example0", ...
    "netCDF_summary", "Sample summary", ...
    "netCDF_title", "Sample Title", ...
    "netCDF_history", "Sample history" ...
    );

rmpath(code_root);
